footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.20

obstacles_laser:
    observation_sources: laser
    laser: {sensor_frame: /laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true}

inflation:
    inflation_radius: 0.2
