global_frame: odom
robot_base_frame: base_link
update_frequency: 2.0
rolling_windown: true
track_unknown_space: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::VoxelLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
